diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.longpaths=true
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=michaeltaye0123@gmail.com
user.name=Michael Taye
user.password=admin@michael@##
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.autocrlf=true
core.excludesfile=C:\Users\HP\Documents\gitignore_global.txt
core.editor="C:\Users\HP\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
core.sshcommand=C:/Windows/System32/OpenSSH/ssh.exe
difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
mergetool.sourcetree.cmd='' 
mergetool.sourcetree.trustexitcode=true
mergetool.sourcetree.keepbackup=false
safe.directory=C:/Users/HP/Downloads/ASD/MyAwesomeApp
credential.helper=manager-core
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/mikeMule/expense_Management_System.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.master.vscode-merge-base=origin/master
lfs.repositoryformatversion=0
lfs.https://github.com/mikeMule/expense_Management_System.git/info/lfs.access=basic
